/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Course: { // root type
    category?: string | null; // String
    coverUrl?: string | null; // String
    description?: string | null; // String
    difficulty?: string | null; // String
    discount?: number | null; // Float
    id?: string | null; // String
    price?: number | null; // Float
    teacherId?: string | null; // String
    title?: string | null; // String
  }
  Lesson: { // root type
    content?: string | null; // String
    duration?: number | null; // Int
    id?: string | null; // String
    moduleId?: string | null; // String
    title?: string | null; // String
    type?: string | null; // String
    videoUrl?: string | null; // String
  }
  Module: { // root type
    courseId?: string | null; // String
    id?: string | null; // String
    title?: string | null; // String
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Course: { // field return type
    category: string | null; // String
    coverUrl: string | null; // String
    description: string | null; // String
    difficulty: string | null; // String
    discount: number | null; // Float
    id: string | null; // String
    modules: Array<NexusGenRootTypes['Module'] | null> | null; // [Module]
    price: number | null; // Float
    teacherId: string | null; // String
    title: string | null; // String
  }
  Lesson: { // field return type
    content: string | null; // String
    duration: number | null; // Int
    id: string | null; // String
    moduleId: string | null; // String
    title: string | null; // String
    type: string | null; // String
    videoUrl: string | null; // String
  }
  Module: { // field return type
    courseId: string | null; // String
    id: string | null; // String
    lessons: Array<NexusGenRootTypes['Lesson'] | null> | null; // [Lesson]
    title: string | null; // String
  }
  Mutation: { // field return type
    createCourse: NexusGenRootTypes['Course'] | null; // Course
    createLesson: NexusGenRootTypes['Lesson'] | null; // Lesson
    createModule: NexusGenRootTypes['Module'] | null; // Module
    deleteCourse: NexusGenRootTypes['Course'] | null; // Course
    deleteLesson: NexusGenRootTypes['Lesson'] | null; // Lesson
    deleteModule: NexusGenRootTypes['Module'] | null; // Module
    updateCourse: NexusGenRootTypes['Course'] | null; // Course
    updateLesson: NexusGenRootTypes['Lesson'] | null; // Lesson
    updateModule: NexusGenRootTypes['Module'] | null; // Module
  }
  Query: { // field return type
    allCourses: Array<NexusGenRootTypes['Course'] | null> | null; // [Course]
    allLessons: Array<NexusGenRootTypes['Lesson'] | null> | null; // [Lesson]
    allModules: Array<NexusGenRootTypes['Module'] | null> | null; // [Module]
    course: NexusGenRootTypes['Course'] | null; // Course
    coursesByTeacher: Array<NexusGenRootTypes['Course'] | null> | null; // [Course]
    lesson: NexusGenRootTypes['Lesson'] | null; // Lesson
    lessonsByModule: Array<NexusGenRootTypes['Lesson'] | null> | null; // [Lesson]
    module: NexusGenRootTypes['Module'] | null; // Module
    modulesByCourse: Array<NexusGenRootTypes['Module'] | null> | null; // [Module]
  }
}

export interface NexusGenFieldTypeNames {
  Course: { // field return type name
    category: 'String'
    coverUrl: 'String'
    description: 'String'
    difficulty: 'String'
    discount: 'Float'
    id: 'String'
    modules: 'Module'
    price: 'Float'
    teacherId: 'String'
    title: 'String'
  }
  Lesson: { // field return type name
    content: 'String'
    duration: 'Int'
    id: 'String'
    moduleId: 'String'
    title: 'String'
    type: 'String'
    videoUrl: 'String'
  }
  Module: { // field return type name
    courseId: 'String'
    id: 'String'
    lessons: 'Lesson'
    title: 'String'
  }
  Mutation: { // field return type name
    createCourse: 'Course'
    createLesson: 'Lesson'
    createModule: 'Module'
    deleteCourse: 'Course'
    deleteLesson: 'Lesson'
    deleteModule: 'Module'
    updateCourse: 'Course'
    updateLesson: 'Lesson'
    updateModule: 'Module'
  }
  Query: { // field return type name
    allCourses: 'Course'
    allLessons: 'Lesson'
    allModules: 'Module'
    course: 'Course'
    coursesByTeacher: 'Course'
    lesson: 'Lesson'
    lessonsByModule: 'Lesson'
    module: 'Module'
    modulesByCourse: 'Module'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createCourse: { // args
      category?: string | null; // String
      description?: string | null; // String
      difficulty?: string | null; // String
      discount?: number | null; // Float
      price?: number | null; // Float
      title: string; // String!
    }
    createLesson: { // args
      content?: string | null; // String
      duration?: number | null; // Int
      moduleId: string; // String!
      title: string; // String!
      type: string; // String!
      videoUrl?: string | null; // String
    }
    createModule: { // args
      courseId: string; // String!
      title: string; // String!
    }
    deleteCourse: { // args
      id: string; // String!
    }
    deleteLesson: { // args
      id: string; // String!
    }
    deleteModule: { // args
      id: string; // String!
    }
    updateCourse: { // args
      category?: string | null; // String
      description?: string | null; // String
      difficulty?: string | null; // String
      discount?: number | null; // Float
      id: string; // String!
      price?: number | null; // Float
      title?: string | null; // String
    }
    updateLesson: { // args
      content?: string | null; // String
      duration?: number | null; // Int
      id: string; // String!
      title?: string | null; // String
      type?: string | null; // String
      videoUrl?: string | null; // String
    }
    updateModule: { // args
      id: string; // String!
      title?: string | null; // String
    }
  }
  Query: {
    course: { // args
      id: string; // String!
    }
    coursesByTeacher: { // args
      teacherId: string; // String!
    }
    lesson: { // args
      id: string; // String!
    }
    lessonsByModule: { // args
      moduleId: string; // String!
    }
    module: { // args
      id: string; // String!
    }
    modulesByCourse: { // args
      courseId: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}