// AUTOGENERATED (GQL10) — ECOMMERCE resolvers
import { PrismaClient } from '../db/generated/client/index.js'

const prisma = new PrismaClient()

export const resolvers = {
  Query: {
    async cartByStudent(_, { studentId }) {
      let cart = await prisma.order.findFirst({
        where: { studentId, status: 'PENDING' },
        include: { items: true, payments: true },
      })
      if (!cart) {
        cart = await prisma.order.create({
          data: { studentId, status: 'PENDING' },
        })
        cart.items = []
        cart.payments = []
      }
      // normalize fields to match schema
      return {
        id: cart.id,
        studentId: cart.studentId,
        status: cart.status,
        items: cart.items || [],
        payments: cart.payments || [],
        updatedAt: cart.updatedAt?.toISOString?.() ?? null,
        createdAt: cart.createdAt?.toISOString?.() ?? null,
      }
    },
  },
  Mutation: {
    async addCartItem(_, { studentId, courseId, quantity }) {
      let cart = await prisma.order.findFirst({ where: { studentId, status: 'PENDING' } })
      if (!cart) {
        cart = await prisma.order.create({ data: { studentId, status: 'PENDING' } })
      }
      const exist = await prisma.orderItem.findFirst({
        where: { orderId: cart.id, courseId },
      })
      if (exist) {
        return prisma.orderItem.update({
          where: { id: exist.id },
          data: { quantity: exist.quantity + Number(quantity || 1) },
        })
      }
      return prisma.orderItem.create({
        data: { orderId: cart.id, courseId, quantity: Number(quantity || 1) },
      })
    },
    async removeCartItem(_, { studentId, orderItemId }) {
      // ensure pending cart exists for student
      await prisma.orderItem.delete({ where: { id: orderItemId } })
      return { ok: true }
    },
    async clearCart(_, { studentId }) {
      const cart = await prisma.order.findFirst({ where: { studentId, status: 'PENDING' } })
      if (!cart) return { ok: true }
      await prisma.orderItem.deleteMany({ where: { orderId: cart.id } })
      return { ok: true }
    },
  },
}
