// AUTOGENERATED (GQL10) — ECOMMERCE typeDefs
import { gql } from 'apollo-server-express'

export const typeDefs = gql`
  scalar JSON

  type Payment {
    id: ID!
    orderId: String!
    provider: String
    status: String
    amount: Float!
    createdAt: String
  }

  type OrderItem {
    id: ID!
    orderId: String!
    courseId: String!
    quantity: Int!
  }

  type Cart {
    id: ID!
    studentId: String!
    status: String!
    items: [OrderItem!]!
    payments: [Payment!]!
    updatedAt: String
    createdAt: String
  }

  type RemoveResult { ok: Boolean! }
  type ClearResult { ok: Boolean! }

  type Query {
    cartByStudent(studentId: String!): Cart
  }

  type Mutation {
    addCartItem(studentId: String!, courseId: String!, quantity: Int = 1): OrderItem!
    removeCartItem(studentId: String!, orderItemId: String!): RemoveResult!
    clearCart(studentId: String!): ClearResult!
  }
`
