import fs from 'fs'
import fsp from 'fs/promises'
import path from 'path'

async function exists(p){try{await fsp.stat(p);return true}catch{return false}}
async function ensureDir(p){await fsp.mkdir(p,{recursive:true})}
async function copyRecursive(src,dest){const stat=await fsp.stat(src);if(stat.isDirectory()){await ensureDir(dest);const entries=await fsp.readdir(src);for(const e of entries){await copyRecursive(path.join(src,e),path.join(dest,e))}}else{await ensureDir(path.dirname(dest));await fsp.copyFile(src,dest)}}
async function copyMissing(src,dest){if(!(await exists(src)))return;const stat=await fsp.stat(src);if(stat.isDirectory()){await ensureDir(dest);const entries=await fsp.readdir(src);for(const e of entries){const s=path.join(src,e);const d=path.join(dest,e);if(!(await exists(d))){await copyRecursive(s,d)}}}else{if(!(await exists(dest))){await ensureDir(path.dirname(dest));await fsp.copyFile(src,dest)}}}

async function migrate(){const cwd=process.cwd();const legacy=path.resolve(cwd,'plugins');if(!fs.existsSync(legacy)){console.log('[migrate] no legacy plugins folder found at '+legacy);return}const targetBase=path.resolve(cwd,'apps/api/src/plugins');await ensureDir(targetBase);const names=(await fsp.readdir(legacy)).filter(d=>fs.statSync(path.join(legacy,d)).isDirectory());for(const name of names){const src=path.join(legacy,name);const dst=path.join(targetBase,name);await ensureDir(dst);const serverSrc=path.join(src,'server');const publicSrc=path.join(src,'public');if(await exists(serverSrc)){const serverDst=path.join(dst,'server');await ensureDir(serverDst);const components=['index.mjs','graphql','db','nexus','permissions.mjs','registerGraphql.mjs','context.js','context.ts','codeServerManager.js','seed.js','seed.mjs','rest','services'];for(const comp of components){const from=path.join(serverSrc,comp);const to=path.join(serverDst,comp);if(await exists(from)){await copyMissing(from,to)}}}if(await exists(publicSrc)){const publicDst=path.join(dst,'public');await copyMissing(publicSrc,publicDst)}const clientJs=path.join(dst,'server','db','client.js');if(await exists(clientJs)){let txt=await fsp.readFile(clientJs,'utf8');if(/from\s+"\.\/generated\/client\/index\.js"/.test(txt)){const genClient=path.join(dst,'server','db','generated','client','index.js');const genIndex=path.join(dst,'server','db','generated','index.js');const hasGenClient=await exists(genClient);const hasGenIndex=await exists(genIndex);if(!hasGenClient&&hasGenIndex){const next=txt.replace('./generated/client/index.js','./generated/index.js');await fsp.writeFile(clientJs,next,'utf8')}}}}console.log('[migrate] done')}
migrate().catch(e=>{console.error('[migrate] error',e);process.exit(1)})